alter table FOODRESERVATIONESHOP_ORDER add constraint FK_FOODRESERVATIONESHOP_ORDER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table FOODRESERVATIONESHOP_ORDER add constraint FK_FOODRESERVATIONESHOP_ORDER_ON_STORE foreign key (STORE_ID) references FOODRESERVATIONESHOP_STORE(ID);
create index IDX_FOODRESERVATIONESHOP_ORDER_ON_USER on FOODRESERVATIONESHOP_ORDER (USER_ID);
create index IDX_FOODRESERVATIONESHOP_ORDER_ON_STORE on FOODRESERVATIONESHOP_ORDER (STORE_ID);
